"""drop dormant normalized tables (D-C)

Revision ID: 19bc6f009bf8
Revises: 475ccaedbd6a
Create Date: 2026-06-18 18:29:15.339908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bc6f009bf8'
down_revision: Union[str, Sequence[str], None] = '475ccaedbd6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_certs_sid'), table_name='student_certificates')
    op.drop_table('student_certificates')
    op.drop_index(op.f('ix_matches_sid'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_student_skills_sid'), table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_student_intern_sid'), table_name='student_internships')
    op.drop_table('student_internships')
    op.drop_table('students')
    op.drop_table('users')
    op.drop_index(op.f('ix_student_proj_sid'), table_name='student_projects')
    op.drop_table('student_projects')
    op.drop_index(op.f('ix_student_edu_sid'), table_name='student_educations')
    op.drop_table('student_educations')
    op.drop_table('reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('target_job', sa.VARCHAR(length=128), nullable=True),
    sa.Column('chapters_json', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_educations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('school', sa.VARCHAR(length=128), nullable=True),
    sa.Column('major', sa.VARCHAR(length=128), nullable=True),
    sa.Column('degree', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_edu_sid'), 'student_educations', ['student_id'], unique=False)
    op.create_table('student_projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_proj_sid'), 'student_projects', ['student_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('students',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('career_intent', sa.VARCHAR(length=128), nullable=True),
    sa.Column('innovation', sa.FLOAT(), nullable=True),
    sa.Column('learning', sa.FLOAT(), nullable=True),
    sa.Column('stress_resistance', sa.FLOAT(), nullable=True),
    sa.Column('communication', sa.FLOAT(), nullable=True),
    sa.Column('internship_level', sa.FLOAT(), nullable=True),
    sa.Column('competitiveness_score', sa.FLOAT(), nullable=True),
    sa.Column('completeness_score', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_internships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_intern_sid'), 'student_internships', ['student_id'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('skill', sa.VARCHAR(length=128), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_skills_sid'), 'student_skills', ['student_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=True),
    sa.Column('job_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('state', sa.VARCHAR(length=32), nullable=True),
    sa.Column('turn_count', sa.INTEGER(), nullable=False),
    sa.Column('messages_json', sa.TEXT(), nullable=True),
    sa.Column('emotion_score', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('job_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('basic_match', sa.FLOAT(), nullable=True),
    sa.Column('skill_match', sa.FLOAT(), nullable=True),
    sa.Column('quality_match', sa.FLOAT(), nullable=True),
    sa.Column('potential_match', sa.FLOAT(), nullable=True),
    sa.Column('total_match', sa.FLOAT(), nullable=True),
    sa.Column('matched_skills', sa.TEXT(), nullable=True),
    sa.Column('missing_skills', sa.TEXT(), nullable=True),
    sa.Column('skill_analysis', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_sid'), 'matches', ['student_id'], unique=False)
    op.create_table('student_certificates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('certificate', sa.VARCHAR(length=256), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_certs_sid'), 'student_certificates', ['student_id'], unique=False)
    # ### end Alembic commands ###
