"""initial schema

Revision ID: 475ccaedbd6a
Revises:
Create Date: 2026-06-18 16:06:38.146474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475ccaedbd6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('final_state', sa.String(length=32), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('ttft_ms', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_sid', 'agent_runs', ['student_id'], unique=False)
    op.create_table('kv_store',
    sa.Column('namespace', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('namespace', 'key')
    )
    op.create_index('ix_kv_ns_sid', 'kv_store', ['namespace', 'student_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('target_job', sa.String(length=128), nullable=True),
    sa.Column('chapters_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('career_intent', sa.String(length=128), nullable=True),
    sa.Column('innovation', sa.Float(), nullable=True),
    sa.Column('learning', sa.Float(), nullable=True),
    sa.Column('stress_resistance', sa.Float(), nullable=True),
    sa.Column('communication', sa.Float(), nullable=True),
    sa.Column('internship_level', sa.Float(), nullable=True),
    sa.Column('competitiveness_score', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('args_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_steps_run', 'agent_steps', ['run_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('job_name', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('messages_json', sa.Text(), nullable=True),
    sa.Column('emotion_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('basic_match', sa.Float(), nullable=True),
    sa.Column('skill_match', sa.Float(), nullable=True),
    sa.Column('quality_match', sa.Float(), nullable=True),
    sa.Column('potential_match', sa.Float(), nullable=True),
    sa.Column('total_match', sa.Float(), nullable=True),
    sa.Column('matched_skills', sa.Text(), nullable=True),
    sa.Column('missing_skills', sa.Text(), nullable=True),
    sa.Column('skill_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matches_sid', 'matches', ['student_id'], unique=False)
    op.create_table('student_certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('certificate', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_certs_sid', 'student_certificates', ['student_id'], unique=False)
    op.create_table('student_educations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('school', sa.String(length=128), nullable=True),
    sa.Column('major', sa.String(length=128), nullable=True),
    sa.Column('degree', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_edu_sid', 'student_educations', ['student_id'], unique=False)
    op.create_table('student_internships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_intern_sid', 'student_internships', ['student_id'], unique=False)
    op.create_table('student_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_proj_sid', 'student_projects', ['student_id'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('skill', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_skills_sid', 'student_skills', ['student_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('ix_student_skills_sid', table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index('ix_student_proj_sid', table_name='student_projects')
    op.drop_table('student_projects')
    op.drop_index('ix_student_intern_sid', table_name='student_internships')
    op.drop_table('student_internships')
    op.drop_index('ix_student_edu_sid', table_name='student_educations')
    op.drop_table('student_educations')
    op.drop_index('ix_student_certs_sid', table_name='student_certificates')
    op.drop_table('student_certificates')
    op.drop_index('ix_matches_sid', table_name='matches')
    op.drop_table('matches')
    op.drop_table('chat_sessions')
    op.drop_index('ix_agent_steps_run', table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_table('students')
    op.drop_table('reports')
    op.drop_index('ix_kv_ns_sid', table_name='kv_store')
    op.drop_table('kv_store')
    op.drop_index('ix_agent_runs_sid', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
